### PR TITLE
New tree feature

### PR DESCRIPTION
**Pull request by jshmyyc**
try to get the whole implementation of map refactor and also add some new feature into the development stage, which should be: 
1. routine algorithm, which should be discarded later for new drone scanning algorithm.
2. ability to add the scanned tree into the tree array that stores the locations of trees.
3. socket channel to let the sender able to send the next destination to drone through front end

### CODE REVIEW

**Comment by McCumskayS** [comment]
Should it not be a merge of NewTreeFeature into development? Since it currently says " merge branch 'development' into NewTreeFeature

**Comment by jshmyyc** [comment]
> Should it not be a merge of NewTreeFeature into development? Since it currently says " merge branch 'development' into NewTreeFeature

**Comment by jshmyyc** [comment]
if looking at the top title, it says I merge into development branch, so I think I am right

**Comment by McCumskayS** [comment]
Yeah that should be fine then, just checking :)

**Pull request merged**
